<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Data Collection and Data Storage | Big Data Analytics</title>
  <meta name="description" content="A guide to data science practitioners making the transition to Big Data." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Data Collection and Data Storage | Big Data Analytics" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://umatter.github.io/BigData/img/cover.png" />
  <meta property="og:description" content="A guide to data science practitioners making the transition to Big Data." />
  <meta name="github-repo" content="umatter/BigData" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Data Collection and Data Storage | Big Data Analytics" />
  
  <meta name="twitter:description" content="A guide to data science practitioners making the transition to Big Data." />
  <meta name="twitter:image" content="https://umatter.github.io/BigData/img/cover.png" />

<meta name="author" content="Ulrich Matter" />


<meta name="date" content="2022-11-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="forms-of-big-data-and-the-data-pipeline.html"/>
<link rel="next" href="big-data-cleaning-and-transformation.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Big Data Analytics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="part"><span><b>I Setting the Scene: Analyzing Big Data</b></span></li>
<li class="chapter" data-level="" data-path="s.html"><a href="s.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="2" data-path="what-is-big-in-big-data.html"><a href="what-is-big-in-big-data.html"><i class="fa fa-check"></i><b>2</b> What is <em>big</em> in “Big Data”?</a></li>
<li class="chapter" data-level="3" data-path="approaches-to-analyzing-big-data.html"><a href="approaches-to-analyzing-big-data.html"><i class="fa fa-check"></i><b>3</b> Approaches to analyzing Big Data</a></li>
<li class="chapter" data-level="4" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html"><i class="fa fa-check"></i><b>4</b> Two domains of Big Data Analytics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html#a-practical-big-p-problem"><i class="fa fa-check"></i><b>4.1</b> A practical <em>big P</em> problem</a></li>
<li class="chapter" data-level="4.2" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html#a-practical-big-n-problem"><i class="fa fa-check"></i><b>4.2</b> A practical <em>big N</em> problem</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html#ols-as-a-point-of-reference"><i class="fa fa-check"></i><b>4.2.1</b> OLS as a point of reference</a></li>
<li class="chapter" data-level="4.2.2" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html#the-uluru-algorithm-as-an-alternative-to-ols"><i class="fa fa-check"></i><b>4.2.2</b> The <em>Uluru</em> algorithm as an alternative to OLS</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="two-domains-of-big-data-analytics.html"><a href="two-domains-of-big-data-analytics.html#conclusion"><i class="fa fa-check"></i><b>4.3</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>II Platform: Software and Computing Resources</b></span></li>
<li class="chapter" data-level="" data-path="p.html"><a href="p.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="5" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html"><i class="fa fa-check"></i><b>5</b> Software: Programming with (Big) Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#domains-of-programming-with-big-data"><i class="fa fa-check"></i><b>5.1</b> Domains of programming with (big) data</a></li>
<li class="chapter" data-level="5.2" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#measuring-r-performance"><i class="fa fa-check"></i><b>5.2</b> Measuring R performance</a></li>
<li class="chapter" data-level="5.3" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#writing-efficient-r-code"><i class="fa fa-check"></i><b>5.3</b> Writing efficient R code</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#memory-allocation-and-growing-objects"><i class="fa fa-check"></i><b>5.3.1</b> Memory allocation and growing objects</a></li>
<li class="chapter" data-level="5.3.2" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#vectorization-in-basic-r-functions"><i class="fa fa-check"></i><b>5.3.2</b> Vectorization in basic R functions</a></li>
<li class="chapter" data-level="5.3.3" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#apply-type-functions-and-vectorization"><i class="fa fa-check"></i><b>5.3.3</b> <code>apply</code>-type functions and vectorization</a></li>
<li class="chapter" data-level="5.3.4" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#avoid-unnecessary-copying"><i class="fa fa-check"></i><b>5.3.4</b> Avoid unnecessary copying</a></li>
<li class="chapter" data-level="5.3.5" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#releasing-memory"><i class="fa fa-check"></i><b>5.3.5</b> Releasing memory</a></li>
<li class="chapter" data-level="5.3.6" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#beyond-r"><i class="fa fa-check"></i><b>5.3.6</b> Beyond R</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#sql-basics"><i class="fa fa-check"></i><b>5.4</b> SQL basics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#first-steps-in-sqlite"><i class="fa fa-check"></i><b>5.4.1</b> First steps in SQL(ite)</a></li>
<li class="chapter" data-level="5.4.2" data-path="software-programming-with-big-data.html"><a href="software-programming-with-big-data.html#joins"><i class="fa fa-check"></i><b>5.4.2</b> Joins</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html"><i class="fa fa-check"></i><b>6</b> Hardware: Computing Resources</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#components-of-a-standard-computing-environment"><i class="fa fa-check"></i><b>6.1</b> Components of a standard computing environment</a></li>
<li class="chapter" data-level="6.2" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#mass-storage"><i class="fa fa-check"></i><b>6.2</b> Mass storage</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#avoid-redundancies"><i class="fa fa-check"></i><b>6.2.1</b> Avoid redundancies</a></li>
<li class="chapter" data-level="6.2.2" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#data-compression"><i class="fa fa-check"></i><b>6.2.2</b> Data compression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#random-access-memory-ram"><i class="fa fa-check"></i><b>6.3</b> Random access memory (RAM)</a></li>
<li class="chapter" data-level="6.4" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#combining-ram-and-hard-disk-virtual-memory"><i class="fa fa-check"></i><b>6.4</b> Combining RAM and hard disk: virtual memory</a></li>
<li class="chapter" data-level="6.5" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#cpu-and-parallelization"><i class="fa fa-check"></i><b>6.5</b> CPU and parallelization</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#naive-multi-session-approach"><i class="fa fa-check"></i><b>6.5.1</b> Naive multi-session approach</a></li>
<li class="chapter" data-level="6.5.2" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#multi-core-and-multi-node-approach"><i class="fa fa-check"></i><b>6.5.2</b> Multi-core and multi-node approach</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#gpus-for-scientific-computing"><i class="fa fa-check"></i><b>6.6</b> GPUs for scientific computing</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#gpus-in-r"><i class="fa fa-check"></i><b>6.6.1</b> GPUs in R</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#the-road-ahead-hardware-made-for-machine-learning"><i class="fa fa-check"></i><b>6.7</b> The road ahead: Hardware made for machine learning</a></li>
<li class="chapter" data-level="6.8" data-path="hardware-computing-resources.html"><a href="hardware-computing-resources.html#insufficient-computing-resources"><i class="fa fa-check"></i><b>6.8</b> Insufficient computing resources?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="distributed-systems.html"><a href="distributed-systems.html"><i class="fa fa-check"></i><b>7</b> Distributed Systems</a>
<ul>
<li class="chapter" data-level="7.1" data-path="distributed-systems.html"><a href="distributed-systems.html#mapreduce"><i class="fa fa-check"></i><b>7.1</b> MapReduce</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="distributed-systems.html"><a href="distributed-systems.html#mapreduce-concept-illustrated-in-r"><i class="fa fa-check"></i><b>7.1.1</b> Map/Reduce Concept Illustrated in R</a></li>
<li class="chapter" data-level="7.1.2" data-path="distributed-systems.html"><a href="distributed-systems.html#mapper"><i class="fa fa-check"></i><b>7.1.2</b> Mapper</a></li>
<li class="chapter" data-level="7.1.3" data-path="distributed-systems.html"><a href="distributed-systems.html#reducer"><i class="fa fa-check"></i><b>7.1.3</b> Reducer</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="distributed-systems.html"><a href="distributed-systems.html#hadoop"><i class="fa fa-check"></i><b>7.2</b> Hadoop</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="distributed-systems.html"><a href="distributed-systems.html#hadoop-word-count-example"><i class="fa fa-check"></i><b>7.2.1</b> Hadoop word count example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="distributed-systems.html"><a href="distributed-systems.html#spark"><i class="fa fa-check"></i><b>7.3</b> Spark</a></li>
<li class="chapter" data-level="7.4" data-path="distributed-systems.html"><a href="distributed-systems.html#spark-with-r"><i class="fa fa-check"></i><b>7.4</b> Spark with R</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="distributed-systems.html"><a href="distributed-systems.html#data-import-and-summary-statistics"><i class="fa fa-check"></i><b>7.4.1</b> Data import and summary statistics</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="distributed-systems.html"><a href="distributed-systems.html#spark-with-sql"><i class="fa fa-check"></i><b>7.5</b> Spark with SQL</a></li>
<li class="chapter" data-level="7.6" data-path="distributed-systems.html"><a href="distributed-systems.html#spark-with-r-sql"><i class="fa fa-check"></i><b>7.6</b> Spark with R + SQL</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cloud-computing.html"><a href="cloud-computing.html"><i class="fa fa-check"></i><b>8</b> Cloud Computing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="cloud-computing.html"><a href="cloud-computing.html#cloud-computing-basics-and-platforms"><i class="fa fa-check"></i><b>8.1</b> Cloud computing basics and platforms</a></li>
<li class="chapter" data-level="8.2" data-path="cloud-computing.html"><a href="cloud-computing.html#scaling-up-in-the-cloud"><i class="fa fa-check"></i><b>8.2</b> Scaling up in the cloud</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="cloud-computing.html"><a href="cloud-computing.html#scaling-up-with-aws-ec2-and-rrstudio"><i class="fa fa-check"></i><b>8.2.1</b> Scaling up with AWS EC2 and R/RStudio</a></li>
<li class="chapter" data-level="8.2.2" data-path="cloud-computing.html"><a href="cloud-computing.html#scaling-up-with-gpus"><i class="fa fa-check"></i><b>8.2.2</b> Scaling up with GPUs</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="cloud-computing.html"><a href="cloud-computing.html#gpus-on-google-colab"><i class="fa fa-check"></i><b>8.3</b> GPUs on Google Colab</a></li>
<li class="chapter" data-level="8.4" data-path="cloud-computing.html"><a href="cloud-computing.html#scaling-out-mapreduce-in-the-cloud"><i class="fa fa-check"></i><b>8.4</b> Scaling out: MapReduce in the cloud</a></li>
</ul></li>
<li class="part"><span><b>III Components of Big Data Analytics</b></span></li>
<li class="chapter" data-level="" data-path="c.html"><a href="c.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="9" data-path="forms-of-big-data-and-the-data-pipeline.html"><a href="forms-of-big-data-and-the-data-pipeline.html"><i class="fa fa-check"></i><b>9</b> Forms of Big Data and the Data Pipeline</a>
<ul>
<li class="chapter" data-level="9.1" data-path="forms-of-big-data-and-the-data-pipeline.html"><a href="forms-of-big-data-and-the-data-pipeline.html#unstructured-semi-structured-structured-data"><i class="fa fa-check"></i><b>9.1</b> Unstructured, semi-structured, structured data</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html"><i class="fa fa-check"></i><b>10</b> Data Collection and Data Storage</a>
<ul>
<li class="chapter" data-level="10.1" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#gathering-and-compilation-of-raw-data"><i class="fa fa-check"></i><b>10.1</b> Gathering and compilation of raw data</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#nyc-taxi-data"><i class="fa fa-check"></i><b>10.1.1</b> NYC taxi data</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#data-import-and-memory-allocation"><i class="fa fa-check"></i><b>10.2</b> Data import and memory allocation</a></li>
<li class="chapter" data-level="10.3" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#efficient-local-data-storage"><i class="fa fa-check"></i><b>10.3</b> Efficient local data storage</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#rdbms-basics"><i class="fa fa-check"></i><b>10.3.1</b> RDBMS basics</a></li>
<li class="chapter" data-level="10.3.2" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#efficient-data-access-indices-and-joins-in-sqlite"><i class="fa fa-check"></i><b>10.3.2</b> Efficient data access: indices and joins in SQLite</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#connecting-r-to-rdbms"><i class="fa fa-check"></i><b>10.4</b> Connecting R to RDBMS</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#creating-a-new-database-with-rsqlite"><i class="fa fa-check"></i><b>10.4.1</b> Creating a new database with <code>RSQLite</code></a></li>
<li class="chapter" data-level="10.4.2" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#importing-data"><i class="fa fa-check"></i><b>10.4.2</b> Importing data</a></li>
<li class="chapter" data-level="10.4.3" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#issue-queries"><i class="fa fa-check"></i><b>10.4.3</b> Issue queries</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#cloud-solutions-for-big-data-storage"><i class="fa fa-check"></i><b>10.5</b> Cloud solutions for (big) data storage</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#easy-to-use-rdbms-in-the-cloud-aws-rds"><i class="fa fa-check"></i><b>10.5.1</b> Easy-to-use RDBMS in the cloud: AWS RDS</a></li>
<li class="chapter" data-level="10.5.2" data-path="data-collection-and-data-storage.html"><a href="data-collection-and-data-storage.html#database-server-in-the-cloud-mariadb-on-an-ec2-instance"><i class="fa fa-check"></i><b>10.5.2</b> Database server in the cloud: MariaDB on an EC2 instance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html"><i class="fa fa-check"></i><b>11</b> Big Data Cleaning and Transformation</a>
<ul>
<li class="chapter" data-level="11.1" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html#out-of-memory-strategies"><i class="fa fa-check"></i><b>11.1</b> ‘Out-of-memory’ strategies</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html#chunking-data-with-the-ff-package"><i class="fa fa-check"></i><b>11.1.1</b> Chunking data with the <code>ff</code>-package</a></li>
<li class="chapter" data-level="11.1.2" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html#memory-mapping-with-bigmemory"><i class="fa fa-check"></i><b>11.1.2</b> Memory mapping with <code>bigmemory</code></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html#typical-cleaning-tasks"><i class="fa fa-check"></i><b>11.2</b> Typical cleaning tasks</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="big-data-cleaning-and-transformation.html"><a href="big-data-cleaning-and-transformation.html#data-preparation-with-ff"><i class="fa fa-check"></i><b>11.2.1</b> Data Preparation with <code>ff</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="descriptive-statistics-and-aggregation.html"><a href="descriptive-statistics-and-aggregation.html"><i class="fa fa-check"></i><b>12</b> Descriptive Statistics and Aggregation</a>
<ul>
<li class="chapter" data-level="12.1" data-path="descriptive-statistics-and-aggregation.html"><a href="descriptive-statistics-and-aggregation.html#data-aggregation-the-split-apply-combine-strategy"><i class="fa fa-check"></i><b>12.1</b> Data aggregation: The ‘split-apply-combine’ strategy</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="descriptive-statistics-and-aggregation.html"><a href="descriptive-statistics-and-aggregation.html#data-aggregation-with-chunked-data-files"><i class="fa fa-check"></i><b>12.1.1</b> Data aggregation with chunked data files</a></li>
<li class="chapter" data-level="12.1.2" data-path="descriptive-statistics-and-aggregation.html"><a href="descriptive-statistics-and-aggregation.html#cross-tabulation-of-ff-vectors"><i class="fa fa-check"></i><b>12.1.2</b> Cross-tabulation of <code>ff</code> vectors</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="descriptive-statistics-and-aggregation.html"><a href="descriptive-statistics-and-aggregation.html#high-speed-in-memory-data-aggregation-with-data.table"><i class="fa fa-check"></i><b>12.2</b> High-speed in-memory data aggregation with <code>data.table</code></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="big-data-visualization.html"><a href="big-data-visualization.html"><i class="fa fa-check"></i><b>13</b> (Big) Data Visualization</a>
<ul>
<li class="chapter" data-level="13.1" data-path="big-data-visualization.html"><a href="big-data-visualization.html#data-exploration-with-ggplot2"><i class="fa fa-check"></i><b>13.1</b> Data exploration with <code>ggplot2</code></a></li>
<li class="chapter" data-level="13.2" data-path="big-data-visualization.html"><a href="big-data-visualization.html#aside-modify-and-create-themes"><i class="fa fa-check"></i><b>13.2</b> Aside: modify and create themes</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="big-data-visualization.html"><a href="big-data-visualization.html#create-your-own-theme-simple-approach"><i class="fa fa-check"></i><b>13.2.1</b> Create your own theme: simple approach</a></li>
<li class="chapter" data-level="13.2.2" data-path="big-data-visualization.html"><a href="big-data-visualization.html#implementing-actual-themes-as-functions."><i class="fa fa-check"></i><b>13.2.2</b> Implementing actual themes as functions.</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="big-data-visualization.html"><a href="big-data-visualization.html#visualize-time-and-space"><i class="fa fa-check"></i><b>13.3</b> Visualize Time and Space</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="big-data-visualization.html"><a href="big-data-visualization.html#preparations"><i class="fa fa-check"></i><b>13.3.1</b> Preparations</a></li>
<li class="chapter" data-level="13.3.2" data-path="big-data-visualization.html"><a href="big-data-visualization.html#pick-up-and-drop-off-locations"><i class="fa fa-check"></i><b>13.3.2</b> Pick-up and drop-off locations</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="big-data-visualization.html"><a href="big-data-visualization.html#aside-change-color-schemes"><i class="fa fa-check"></i><b>13.4</b> Aside: change color schemes</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html"><i class="fa fa-check"></i><b>14</b> Bottle Necks in Local Big Data Analytics</a>
<ul>
<li class="chapter" data-level="14.1" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#case-study-data-import-and-memory-allocation"><i class="fa fa-check"></i><b>14.1</b> Case study: Data Import and Memory Allocation</a></li>
<li class="chapter" data-level="14.2" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#case-study-loops-memory-and-vectorization"><i class="fa fa-check"></i><b>14.2</b> Case Study: Loops, Memory, and Vectorization</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#preparation"><i class="fa fa-check"></i><b>14.2.1</b> Preparation</a></li>
<li class="chapter" data-level="14.2.2" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#naïve-approach-ignorant-of-r"><i class="fa fa-check"></i><b>14.2.2</b> Naïve Approach (ignorant of R)</a></li>
<li class="chapter" data-level="14.2.3" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#improvement-1-pre-allocation-of-memory"><i class="fa fa-check"></i><b>14.2.3</b> Improvement 1: Pre-allocation of memory</a></li>
<li class="chapter" data-level="14.2.4" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#improvement-2-exploit-vectorization"><i class="fa fa-check"></i><b>14.2.4</b> Improvement 2: Exploit vectorization</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#case-study-bootstrapping-and-parallel-processing"><i class="fa fa-check"></i><b>14.3</b> Case study: Bootstrapping and Parallel Processing</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#parallelization-with-an-ec2-instance-1"><i class="fa fa-check"></i><b>14.3.1</b> Parallelization with an EC2 instance</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="bottle-necks-in-local-big-data-analytics.html"><a href="bottle-necks-in-local-big-data-analytics.html#case-study-efficient-fixed-effects-estimation"><i class="fa fa-check"></i><b>14.4</b> Case Study: Efficient Fixed Effects Estimation</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html"><i class="fa fa-check"></i><b>15</b> GPUs and Machine Learning</a>
<ul>
<li class="chapter" data-level="15.1" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html#tensorflowkeras-example-predict-housing-prices"><i class="fa fa-check"></i><b>15.1</b> Tensorflow/Keras example: predict housing prices</a></li>
<li class="chapter" data-level="15.2" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html#data-preparation-1"><i class="fa fa-check"></i><b>15.2</b> Data preparation</a></li>
<li class="chapter" data-level="15.3" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html#model-specification"><i class="fa fa-check"></i><b>15.3</b> Model specification</a></li>
<li class="chapter" data-level="15.4" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html#training-and-prediction"><i class="fa fa-check"></i><b>15.4</b> Training and prediction</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="gpus-and-machine-learning.html"><a href="gpus-and-machine-learning.html#a-word-of-caution"><i class="fa fa-check"></i><b>15.4.1</b> A word of caution</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Application: Topics in Big Data Econometrics</b></span></li>
<li class="chapter" data-level="" data-path="a.html"><a href="a.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="16" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html"><i class="fa fa-check"></i><b>16</b> Regression Analysis and Categorization with Spark and R</a>
<ul>
<li class="chapter" data-level="16.1" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html#simple-regression-analysis"><i class="fa fa-check"></i><b>16.1</b> Simple regression analysis</a></li>
<li class="chapter" data-level="16.2" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html#machine-learning-for-classification"><i class="fa fa-check"></i><b>16.2</b> Machine learning for classification</a></li>
<li class="chapter" data-level="16.3" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html#building-machine-learning-pipelines-with-r-and-spark"><i class="fa fa-check"></i><b>16.3</b> Building machine learning pipelines with R and Spark</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html#set-up-and-data-import"><i class="fa fa-check"></i><b>16.3.1</b> Set up and data import</a></li>
<li class="chapter" data-level="16.3.2" data-path="regression-analysis-and-categorization-with-spark-and-r.html"><a href="regression-analysis-and-categorization-with-spark-and-r.html#building-the-pipeline"><i class="fa fa-check"></i><b>16.3.2</b> Building the pipeline</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="large-scale-text-analysis-with-sparklyr.html"><a href="large-scale-text-analysis-with-sparklyr.html"><i class="fa fa-check"></i><b>17</b> Large-scale Text Analysis with sparklyr</a>
<ul>
<li class="chapter" data-level="17.1" data-path="large-scale-text-analysis-with-sparklyr.html"><a href="large-scale-text-analysis-with-sparklyr.html#getting-started-import-preparation-and-word-frequencies"><i class="fa fa-check"></i><b>17.1</b> Getting started: import, preparation, and word frequencies</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendix-a.html"><a href="appendix-a.html"><i class="fa fa-check"></i><b>A</b> Appendix A</a>
<ul>
<li class="chapter" data-level="A.1" data-path="appendix-a.html"><a href="appendix-a.html#github"><i class="fa fa-check"></i><b>A.1</b> GitHub</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="appendix-a.html"><a href="appendix-a.html#initiate-a-new-repository"><i class="fa fa-check"></i><b>A.1.1</b> Initiate a new repository</a></li>
<li class="chapter" data-level="A.1.2" data-path="appendix-a.html"><a href="appendix-a.html#clone-this-courses-repository"><i class="fa fa-check"></i><b>A.1.2</b> Clone this course’s repository</a></li>
<li class="chapter" data-level="A.1.3" data-path="appendix-a.html"><a href="appendix-a.html#fork-this-courses-repository"><i class="fa fa-check"></i><b>A.1.3</b> Fork this course’s repository</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="appendix-b.html"><a href="appendix-b.html"><i class="fa fa-check"></i><b>B</b> Appendix B</a>
<ul>
<li class="chapter" data-level="B.1" data-path="appendix-b.html"><a href="appendix-b.html#data-types-and-memorystorage"><i class="fa fa-check"></i><b>B.1</b> Data types and memory/storage</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="appendix-b.html"><a href="appendix-b.html#example-in-r-data-types-and-information-storage"><i class="fa fa-check"></i><b>B.1.1</b> Example in R: Data types and information storage</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="appendix-b.html"><a href="appendix-b.html#data-structures"><i class="fa fa-check"></i><b>B.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="B.2.1" data-path="appendix-b.html"><a href="appendix-b.html#vectors-vs-factors-in-r"><i class="fa fa-check"></i><b>B.2.1</b> Vectors vs Factors in R</a></li>
<li class="chapter" data-level="B.2.2" data-path="appendix-b.html"><a href="appendix-b.html#matricesarrays"><i class="fa fa-check"></i><b>B.2.2</b> Matrices/Arrays</a></li>
<li class="chapter" data-level="B.2.3" data-path="appendix-b.html"><a href="appendix-b.html#data-frames-tibbles-and-data-tables"><i class="fa fa-check"></i><b>B.2.3</b> Data frames, tibbles, and data tables</a></li>
<li class="chapter" data-level="B.2.4" data-path="appendix-b.html"><a href="appendix-b.html#lists"><i class="fa fa-check"></i><b>B.2.4</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="appendix-b.html"><a href="appendix-b.html#r-tools-to-investigate-structures-and-types"><i class="fa fa-check"></i><b>B.3</b> R-tools to investigate structures and types</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="appendix-c.html"><a href="appendix-c.html"><i class="fa fa-check"></i><b>C</b> Appendix C</a>
<ul>
<li class="chapter" data-level="C.1" data-path="appendix-c.html"><a href="appendix-c.html#install-hadoop-on-ubuntu-linux"><i class="fa fa-check"></i><b>C.1</b> Install Hadoop (on Ubuntu Linux)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://umatter.github.io" target="blank">umatter.github.io</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Big Data Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-collection-and-data-storage" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Data Collection and Data Storage<a href="data-collection-and-data-storage.html#data-collection-and-data-storage" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="gathering-and-compilation-of-raw-data" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Gathering and compilation of raw data<a href="data-collection-and-data-storage.html#gathering-and-compilation-of-raw-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="nyc-taxi-data" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> NYC taxi data<a href="data-collection-and-data-storage.html#nyc-taxi-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The NYC Taxi &amp; Limousine Commission (TLC) provides detailed data on all trip records including pick-up and drop-off times/locations. When combining all available trip records (2009-2018), we get a rather large data set of over 200GB. The code examples below illustrate how to collect and compile the entire data set. In order to avoid long computing times, the code examples shown below are based on a small sub-set of the actual raw data (however, all examples involving virtual memory, are in theory scalable to the extent of the entire raw data set).</p>
<p>The raw data consists of several monthly CSV-files and can be downloaded via the <a href="https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page">TLC’s website</a>. The following short R-script automates the downloading of all available trip-record files. <em>NOTE</em>: Downloading all files can take several hours and will occupy over 200GB!</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="data-collection-and-data-storage.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb195-2"><a href="data-collection-and-data-storage.html#cb195-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fetch all TLC trip recrods</span></span>
<span id="cb195-3"><a href="data-collection-and-data-storage.html#cb195-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Data source: </span></span>
<span id="cb195-4"><a href="data-collection-and-data-storage.html#cb195-4" aria-hidden="true" tabindex="-1"></a><span class="co"># https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page</span></span>
<span id="cb195-5"><a href="data-collection-and-data-storage.html#cb195-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: Monthly csv files from urls</span></span>
<span id="cb195-6"><a href="data-collection-and-data-storage.html#cb195-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Output: one large csv file</span></span>
<span id="cb195-7"><a href="data-collection-and-data-storage.html#cb195-7" aria-hidden="true" tabindex="-1"></a><span class="co"># UM, St. Gallen, January 2019</span></span>
<span id="cb195-8"><a href="data-collection-and-data-storage.html#cb195-8" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb195-9"><a href="data-collection-and-data-storage.html#cb195-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-10"><a href="data-collection-and-data-storage.html#cb195-10" aria-hidden="true" tabindex="-1"></a><span class="co"># SET UP -----------------</span></span>
<span id="cb195-11"><a href="data-collection-and-data-storage.html#cb195-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-12"><a href="data-collection-and-data-storage.html#cb195-12" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb195-13"><a href="data-collection-and-data-storage.html#cb195-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb195-14"><a href="data-collection-and-data-storage.html#cb195-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span>
<span id="cb195-15"><a href="data-collection-and-data-storage.html#cb195-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb195-16"><a href="data-collection-and-data-storage.html#cb195-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-17"><a href="data-collection-and-data-storage.html#cb195-17" aria-hidden="true" tabindex="-1"></a><span class="co"># fix vars</span></span>
<span id="cb195-18"><a href="data-collection-and-data-storage.html#cb195-18" aria-hidden="true" tabindex="-1"></a>BASE_URL <span class="ot">&lt;-</span> <span class="st">&quot;https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2018-01.csv&quot;</span></span>
<span id="cb195-19"><a href="data-collection-and-data-storage.html#cb195-19" aria-hidden="true" tabindex="-1"></a>OUTPUT_PATH <span class="ot">&lt;-</span> <span class="st">&quot;data/tlc_trips.csv&quot;</span></span>
<span id="cb195-20"><a href="data-collection-and-data-storage.html#cb195-20" aria-hidden="true" tabindex="-1"></a>START_DATE <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2009-01-01&quot;</span>)</span>
<span id="cb195-21"><a href="data-collection-and-data-storage.html#cb195-21" aria-hidden="true" tabindex="-1"></a>END_DATE <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2018-06-01&quot;</span>)</span>
<span id="cb195-22"><a href="data-collection-and-data-storage.html#cb195-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-23"><a href="data-collection-and-data-storage.html#cb195-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-24"><a href="data-collection-and-data-storage.html#cb195-24" aria-hidden="true" tabindex="-1"></a><span class="co"># BUILD URLS -----------</span></span>
<span id="cb195-25"><a href="data-collection-and-data-storage.html#cb195-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-26"><a href="data-collection-and-data-storage.html#cb195-26" aria-hidden="true" tabindex="-1"></a><span class="co"># parse base url</span></span>
<span id="cb195-27"><a href="data-collection-and-data-storage.html#cb195-27" aria-hidden="true" tabindex="-1"></a>base_url <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">&quot;2018-01.csv&quot;</span>, <span class="st">&quot;&quot;</span>, BASE_URL)</span>
<span id="cb195-28"><a href="data-collection-and-data-storage.html#cb195-28" aria-hidden="true" tabindex="-1"></a><span class="co"># build urls</span></span>
<span id="cb195-29"><a href="data-collection-and-data-storage.html#cb195-29" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span> START_DATE,</span>
<span id="cb195-30"><a href="data-collection-and-data-storage.html#cb195-30" aria-hidden="true" tabindex="-1"></a>                   <span class="at">to =</span> END_DATE,</span>
<span id="cb195-31"><a href="data-collection-and-data-storage.html#cb195-31" aria-hidden="true" tabindex="-1"></a>                   <span class="at">by =</span> <span class="st">&quot;month&quot;</span>)</span>
<span id="cb195-32"><a href="data-collection-and-data-storage.html#cb195-32" aria-hidden="true" tabindex="-1"></a>year_months <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">&quot;-01$&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="fu">as.character</span>(dates))</span>
<span id="cb195-33"><a href="data-collection-and-data-storage.html#cb195-33" aria-hidden="true" tabindex="-1"></a>data_urls <span class="ot">&lt;-</span> <span class="fu">paste0</span>(base_url, year_months, <span class="st">&quot;.csv&quot;</span>)</span>
<span id="cb195-34"><a href="data-collection-and-data-storage.html#cb195-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-35"><a href="data-collection-and-data-storage.html#cb195-35" aria-hidden="true" tabindex="-1"></a><span class="co"># FETCH AND STACK CSVS ----------------</span></span>
<span id="cb195-36"><a href="data-collection-and-data-storage.html#cb195-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb195-37"><a href="data-collection-and-data-storage.html#cb195-37" aria-hidden="true" tabindex="-1"></a><span class="co"># download, parse all files, write them to one csv</span></span>
<span id="cb195-38"><a href="data-collection-and-data-storage.html#cb195-38" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (url <span class="cf">in</span> data_urls) {</span>
<span id="cb195-39"><a href="data-collection-and-data-storage.html#cb195-39" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb195-40"><a href="data-collection-and-data-storage.html#cb195-40" aria-hidden="true" tabindex="-1"></a>     <span class="co"># download to temporary file</span></span>
<span id="cb195-41"><a href="data-collection-and-data-storage.html#cb195-41" aria-hidden="true" tabindex="-1"></a>     tmpfile <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb195-42"><a href="data-collection-and-data-storage.html#cb195-42" aria-hidden="true" tabindex="-1"></a>     <span class="fu">download.file</span>(url, <span class="at">destfile =</span> tmpfile)</span>
<span id="cb195-43"><a href="data-collection-and-data-storage.html#cb195-43" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb195-44"><a href="data-collection-and-data-storage.html#cb195-44" aria-hidden="true" tabindex="-1"></a>     <span class="co"># parse downloaded file, write to output csv, remove tempfile</span></span>
<span id="cb195-45"><a href="data-collection-and-data-storage.html#cb195-45" aria-hidden="true" tabindex="-1"></a>     csv_parsed <span class="ot">&lt;-</span> <span class="fu">fread</span>(tmpfile)</span>
<span id="cb195-46"><a href="data-collection-and-data-storage.html#cb195-46" aria-hidden="true" tabindex="-1"></a>     <span class="fu">fwrite</span>(csv_parsed,</span>
<span id="cb195-47"><a href="data-collection-and-data-storage.html#cb195-47" aria-hidden="true" tabindex="-1"></a>            <span class="at">file =</span>  OUTPUT_PATH,</span>
<span id="cb195-48"><a href="data-collection-and-data-storage.html#cb195-48" aria-hidden="true" tabindex="-1"></a>            <span class="at">append =</span> <span class="cn">TRUE</span>)</span>
<span id="cb195-49"><a href="data-collection-and-data-storage.html#cb195-49" aria-hidden="true" tabindex="-1"></a>     <span class="fu">unlink</span>(tmpfile)</span>
<span id="cb195-50"><a href="data-collection-and-data-storage.html#cb195-50" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb195-51"><a href="data-collection-and-data-storage.html#cb195-51" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
</div>
<div id="data-import-and-memory-allocation" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Data import and memory allocation<a href="data-collection-and-data-storage.html#data-import-and-memory-allocation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- When writing the data-import part of a program, we could use the traditional `read.csv()` or `fread()` from the `data.table`-package. The result is very similar (in many situations, the differences of the resulting objects would not matter at all). -->
<!-- ```{r message=FALSE, warning=FALSE} -->
<!-- # read a CSV-file the 'traditional way' -->
<!-- flights <- read.csv("data/flights.csv") -->
<!-- class(flights) -->
<!-- # alternative (needs the data.table package) -->
<!-- library(data.table) -->
<!-- flights <- fread("data/flights.csv") -->
<!-- class(flights) -->
<!-- ``` -->
<!-- However, the latter approach is usually much faster. -->
<!-- ```{r} -->
<!-- system.time(flights <- read.csv("data/flights.csv")) -->
<!-- system.time(flights <- fread("data/flights.csv")) -->
<!-- ``` -->
<p>Consider the first steps of a data pipeline in R. The first part of our script to import and clean the data looks as follows.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="data-collection-and-data-storage.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="do">###########################################################</span></span>
<span id="cb196-2"><a href="data-collection-and-data-storage.html#cb196-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Big Data Statistics: Flights data import and preparation</span></span>
<span id="cb196-3"><a href="data-collection-and-data-storage.html#cb196-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb196-4"><a href="data-collection-and-data-storage.html#cb196-4" aria-hidden="true" tabindex="-1"></a><span class="co"># U. Matter, January 2019</span></span>
<span id="cb196-5"><a href="data-collection-and-data-storage.html#cb196-5" aria-hidden="true" tabindex="-1"></a><span class="do">###########################################################</span></span>
<span id="cb196-6"><a href="data-collection-and-data-storage.html#cb196-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-7"><a href="data-collection-and-data-storage.html#cb196-7" aria-hidden="true" tabindex="-1"></a><span class="co"># SET UP -----------------</span></span>
<span id="cb196-8"><a href="data-collection-and-data-storage.html#cb196-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-9"><a href="data-collection-and-data-storage.html#cb196-9" aria-hidden="true" tabindex="-1"></a><span class="co"># fix variables</span></span>
<span id="cb196-10"><a href="data-collection-and-data-storage.html#cb196-10" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="ot">&lt;-</span> <span class="st">&quot;data/flights.csv&quot;</span></span>
<span id="cb196-11"><a href="data-collection-and-data-storage.html#cb196-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-12"><a href="data-collection-and-data-storage.html#cb196-12" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA IMPORT ----------------</span></span>
<span id="cb196-13"><a href="data-collection-and-data-storage.html#cb196-13" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(DATA_PATH)</span>
<span id="cb196-14"><a href="data-collection-and-data-storage.html#cb196-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-15"><a href="data-collection-and-data-storage.html#cb196-15" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA PREPARATION --------</span></span>
<span id="cb196-16"><a href="data-collection-and-data-storage.html#cb196-16" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights[,<span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">3</span>]</span></code></pre></div>
<p>When running this script, we notice that some of the steps need a noticeable amount of time to process. Moreover, while none of these steps obviously involves a lot of computation (such as a matrix inversion or numerical optimization), it quite likely involves memory allocation. We first read data into RAM (allocated to R by our operating system). It turns out that there are different ways to allocate RAM when reading data from a CSV file. Depending on the amount of data to be read in, one or the other approach might be faster. We first investigate the RAM allocation in R with <code>mem_change()</code> and <code>mem_used()</code>.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="data-collection-and-data-storage.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SET UP -----------------</span></span>
<span id="cb197-2"><a href="data-collection-and-data-storage.html#cb197-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-3"><a href="data-collection-and-data-storage.html#cb197-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fix variables</span></span>
<span id="cb197-4"><a href="data-collection-and-data-storage.html#cb197-4" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="ot">&lt;-</span> <span class="st">&quot;data/flights.csv&quot;</span></span>
<span id="cb197-5"><a href="data-collection-and-data-storage.html#cb197-5" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb197-6"><a href="data-collection-and-data-storage.html#cb197-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pryr) </span>
<span id="cb197-7"><a href="data-collection-and-data-storage.html#cb197-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-8"><a href="data-collection-and-data-storage.html#cb197-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-9"><a href="data-collection-and-data-storage.html#cb197-9" aria-hidden="true" tabindex="-1"></a><span class="co"># check how much memory is used by R (overall)</span></span>
<span id="cb197-10"><a href="data-collection-and-data-storage.html#cb197-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mem_used</span>()</span></code></pre></div>
<pre><code>## 1.73 GB</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="data-collection-and-data-storage.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the change in memory due to each step</span></span>
<span id="cb199-2"><a href="data-collection-and-data-storage.html#cb199-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb199-3"><a href="data-collection-and-data-storage.html#cb199-3" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA IMPORT ----------------</span></span>
<span id="cb199-4"><a href="data-collection-and-data-storage.html#cb199-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mem_change</span>(flights <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(DATA_PATH))</span></code></pre></div>
<pre><code>## 4.04 MB</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="data-collection-and-data-storage.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA PREPARATION --------</span></span>
<span id="cb201-2"><a href="data-collection-and-data-storage.html#cb201-2" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights[,<span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">3</span>]</span>
<span id="cb201-3"><a href="data-collection-and-data-storage.html#cb201-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb201-4"><a href="data-collection-and-data-storage.html#cb201-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check how much memory is used by R now</span></span>
<span id="cb201-5"><a href="data-collection-and-data-storage.html#cb201-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mem_used</span>()</span></code></pre></div>
<pre><code>## 1.73 GB</code></pre>
<p>The last result is kind of interesting. The object <code>flights</code> must have been larger right after importing it than at the end of the script. We have thrown out several variables, after all. Why does R still use that much memory? R does by default not ‘clean up’ memory unless it is really necessary (meaning no more memory is available). In this case, R has still way more memory available from the operating system, thus there is no need to ‘collect the garbage’ yet. However, we can force R to collect the garbage on the spot with <code>gc()</code>. This can be helpful to better keep track of the memory needed by an analytics script.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="data-collection-and-data-storage.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gc</span>()</span></code></pre></div>
<pre><code>##             used (Mb) gc trigger   (Mb)  max used
## Ncells   6552113  350   10573261  564.7  10573261
## Vcells 169868041 1296  401578444 3063.9 334581381
##          (Mb)
## Ncells  564.7
## Vcells 2552.7</code></pre>
<p>Now, let’s see how we can improve the performance of this script with regard to memory allocation. Most memory is allocated when importing the file. Obviously, any improvement of the script must still result in importing all the data. However, there are different ways to read data into RAM. <code>read.csv()</code> reads all lines of a csv file consecutively. In contrast, <code>data.table::fread()</code> first ‘maps’ the data file into memory and only then actually reads it in line by line. This involves an additional initial step, but the larger the file, the less relevant is this first step with regard to the total time needed to read all the data into memory. By switching on the <code>verbose</code> option, we can actually see what <code>fread</code> is doing.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="data-collection-and-data-storage.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb205-2"><a href="data-collection-and-data-storage.html#cb205-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:pryr&#39;:
## 
##     address</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="data-collection-and-data-storage.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA IMPORT ----------------</span></span>
<span id="cb208-2"><a href="data-collection-and-data-storage.html#cb208-2" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="fu">fread</span>(DATA_PATH, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##   OpenMP version (_OPENMP)       201511
##   omp_get_num_procs()            12
##   R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
##   R_DATATABLE_NUM_THREADS        unset
##   R_DATATABLE_THROTTLE           unset (default 1024)
##   omp_get_thread_limit()         2147483647
##   omp_get_max_threads()          12
##   OMP_THREAD_LIMIT               unset
##   OMP_NUM_THREADS                unset
##   RestoreAfterFork               true
##   data.table is using 6 threads with throttle==1024. See ?setDTthreads.
## Input contains no \n. Taking this to be a filename to open
## [01] Check arguments
##   Using 6 threads (omp_get_max_threads()=12, nth=6)
##   NAstrings = [&lt;&lt;NA&gt;&gt;]
##   None of the NAstrings look like numbers.
##   show progress = 0
##   0/1 column will be read as integer
## [02] Opening the file
##   Opening file data/flights.csv
##   File opened, size = 29.53MB (30960660 bytes).
##   Memory mapped ok
## [03] Detect and skip BOM
## [04] Arrange mmap to be \0 terminated
##   \n has been found in the input and different lines can end with different line endings (e.g. mixed \n and \r\n in one file). This is common and ideal.
## [05] Skipping initial rows if needed
##   Positioned on line 1 starting: &lt;&lt;year,month,day,dep_time,sched_&gt;&gt;
## [06] Detect separator, quoting rule, and ncolumns
##   Detecting sep automatically ...
##   sep=&#39;,&#39;  with 100 lines of 19 fields using quote rule 0
##   Detected 19 columns on line 1. This line is either column names or first data row. Line starts as: &lt;&lt;year,month,day,dep_time,sched_&gt;&gt;
##   Quote rule picked = 0
##   fill=false and the most number of columns found is 19
## [07] Detect column types, good nrow estimate and whether first row is column names
##   Number of sampling jump points = 100 because (30960659 bytes from row 1 to eof) / (2 * 8882 jump0size) == 1742
##   Type codes (jump 000)    : 555555555C5CCC5555B  Quote rule 0
##   Type codes (jump 100)    : 555555555C5CCC5555B  Quote rule 0
##   &#39;header&#39; determined to be true due to column 1 containing a string on row 1 and a lower type (int32) in the rest of the 10048 sample rows
##   =====
##   Sampled 10048 rows (handled \n inside quoted fields) at 101 jump points
##   Bytes from first data row on line 2 to the end of last row: 30960501
##   Line length: mean=92.03 sd=3.56 min=68 max=98
##   Estimated number of rows: 30960501 / 92.03 = 336403
##   Initial alloc = 370043 rows (336403 + 9%) using bytes/max(mean-2*sd,min) clamped between [1.1*estn, 2.0*estn]
##   =====
## [08] Assign column names
## [09] Apply user overrides on column types
##   After 0 type and 0 drop user overrides : 555555555C5CCC5555B
## [10] Allocate memory for the datatable
##   Allocating 19 column slots (19 - 0 dropped) with 370043 rows
## [11] Read the data
##   jumps=[0..30), chunk_size=1032016, total_size=30960501
## Read 336776 rows x 19 columns from 29.53MB (30960660 bytes) file in 00:00.076 wall clock time
## [12] Finalizing the datatable
##   Type counts:
##         14 : int32     &#39;5&#39;
##          1 : float64   &#39;B&#39;
##          4 : string    &#39;C&#39;
## =============================
##    0.000s (  0%) Memory map 0.029GB file
##    0.003s (  5%) sep=&#39;,&#39; ncol=19 and header detection
##    0.000s (  0%) Column type detection using 10048 sample rows
##    0.001s (  1%) Allocation of 370043 rows x 19 cols (0.033GB) of which 336776 ( 91%) rows used
##    0.071s ( 94%) Reading 30 chunks (0 swept) of 0.984MB (each chunk 11225 rows) using 6 threads
##    +    0.018s ( 23%) Parse to row-major thread buffers (grown 0 times)
##    +    0.034s ( 45%) Transpose
##    +    0.020s ( 26%) Waiting
##    0.000s (  0%) Rereading 0 columns due to out-of-sample type exceptions
##    0.076s        Total</code></pre>
<p>Let’s put it all together and look at the memory changes and usage. For a fair comparison, we first have to delete <code>flights</code> and collect the garbage with <code>gc()</code>.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="data-collection-and-data-storage.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SET UP -----------------</span></span>
<span id="cb210-2"><a href="data-collection-and-data-storage.html#cb210-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb210-3"><a href="data-collection-and-data-storage.html#cb210-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fix variables</span></span>
<span id="cb210-4"><a href="data-collection-and-data-storage.html#cb210-4" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="ot">&lt;-</span> <span class="st">&quot;data/flights.csv&quot;</span></span>
<span id="cb210-5"><a href="data-collection-and-data-storage.html#cb210-5" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb210-6"><a href="data-collection-and-data-storage.html#cb210-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pryr) </span>
<span id="cb210-7"><a href="data-collection-and-data-storage.html#cb210-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb210-8"><a href="data-collection-and-data-storage.html#cb210-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb210-9"><a href="data-collection-and-data-storage.html#cb210-9" aria-hidden="true" tabindex="-1"></a><span class="co"># housekeeping</span></span>
<span id="cb210-10"><a href="data-collection-and-data-storage.html#cb210-10" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb210-11"><a href="data-collection-and-data-storage.html#cb210-11" aria-hidden="true" tabindex="-1"></a><span class="fu">gc</span>()</span></code></pre></div>
<pre><code>##             used   (Mb) gc trigger   (Mb)  max used
## Ncells   6610653  353.1   10573261  564.7  10573261
## Vcells 166854131 1273.0  401578444 3063.9 334581381
##          (Mb)
## Ncells  564.7
## Vcells 2552.7</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="data-collection-and-data-storage.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the change in memory due to each step</span></span>
<span id="cb212-2"><a href="data-collection-and-data-storage.html#cb212-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb212-3"><a href="data-collection-and-data-storage.html#cb212-3" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA IMPORT ----------------</span></span>
<span id="cb212-4"><a href="data-collection-and-data-storage.html#cb212-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mem_change</span>(flights <span class="ot">&lt;-</span> <span class="fu">fread</span>(DATA_PATH))</span></code></pre></div>
<pre><code>## 35.8 MB</code></pre>
</div>
<div id="efficient-local-data-storage" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Efficient local data storage<a href="data-collection-and-data-storage.html#efficient-local-data-storage" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- So far, we have primarily been concerned with situations in which a data set is too large to fit into RAM, making an analysis of these data either impossible or very slow (inefficient) when using standard tools. Thus, we have explored concepts and tools that help us use the available RAM (and virtual memory) most efficiently for data analysis tasks. -->
<p>In this section, we are concerned with <span class="math inline">\((I)\)</span> how we can store large data sets permanently on a mass storage device in an efficient way (here, efficient can be understood as ‘not taking up too much space’) and <span class="math inline">\((II)\)</span> how we can load (parts of) this data set in an efficient way (here, efficient~fast) for analysis.</p>
<p>We look at this problem in two situations:</p>
<ul>
<li>The data needs to be stored locally (e.g., on the hard disk of our laptop).</li>
<li>The data can be stored on a server ‘in the cloud’.</li>
</ul>
<p>Various tools have been developed over the last few years to improve the efficiency of storing and accessing large amounts of data (see <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>, chapters 5 and 6 for an overview). Here, we focus on the basic concept of Relational Database Systems (RDBMS) and a well-known tool based on this concept, the Structured Query Language (SQL; more specifically, SQLite)</p>
<div id="rdbms-basics" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> RDBMS basics<a href="data-collection-and-data-storage.html#rdbms-basics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>RDBMSs have two key features that tackle the two efficiency concerns mentioned above:</p>
<ul>
<li><p>The <em>relational data model</em>: The overall data set is split by columns (covariates) into tables in order to reduce the storage of redundant variable-value repetitions. The resulting database tables are then linked via key-variables (unique identifiers). Thus (simply put), each type of entity on which observations exist resides in its own database table. Within this table, each observation has it’s unique id. Keeping the data in such a structure is very efficient in terms of storage space used.</p></li>
<li><p><em>Indexing</em>: The key-columns of the database tables are indexed, meaning (in simple terms) ordered on disk. Indexing a table takes time but it has to be performed only once (unless the content of the table changes). The resulting index is then stored on disk as part of the database. These indices substantially reduce the number of disk accesses required to query/find specific observations. Thus, they make the loading of specific parts of the data for analysis much more efficient.</p></li>
</ul>
<p>The loading/querying of data from an RDBMS typically involves the selection of specific observations (rows) and covariates (columns) from different tables. Due to the indexing, observations are selected efficiently, and the defined relations between tables (via keys) facilitate the joining of columns to a new table (the queried data).</p>
<!-- ### Row-based vs column-based databases -->
</div>
<div id="efficient-data-access-indices-and-joins-in-sqlite" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Efficient data access: indices and joins in SQLite<a href="data-collection-and-data-storage.html#efficient-data-access-indices-and-joins-in-sqlite" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So far we have only had a look at the very basics of writing SQL code. Let us now further explore SQLite as an easy-to-use and easy-to-set-up relational database solution. In a second step we then look at how to connect to a local SQLite database from within R. First, we switch to the Terminal tab in RStudio, set up a new database called <code>air.sqlite</code>, and import the csv-file <code>flights.csv</code> (used in previous chapters) as a first table.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb214-1"><a href="data-collection-and-data-storage.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="co"># switch to data directory</span></span>
<span id="cb214-2"><a href="data-collection-and-data-storage.html#cb214-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> data</span>
<span id="cb214-3"><a href="data-collection-and-data-storage.html#cb214-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create database and run sqlite</span></span>
<span id="cb214-4"><a href="data-collection-and-data-storage.html#cb214-4" aria-hidden="true" tabindex="-1"></a><span class="ex">sqlite3</span> air.sqlite</span></code></pre></div>
<div class="sourceCode" id="cb215"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb215-1"><a href="data-collection-and-data-storage.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- import csvs</span></span>
<span id="cb215-2"><a href="data-collection-and-data-storage.html#cb215-2" aria-hidden="true" tabindex="-1"></a>.<span class="kw">mode</span> csv</span>
<span id="cb215-3"><a href="data-collection-and-data-storage.html#cb215-3" aria-hidden="true" tabindex="-1"></a>.import flights.csv flights</span></code></pre></div>
<p>We check if everything worked out well via the <code>.tables</code> and <code>.schema</code> commands.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb216-1"><a href="data-collection-and-data-storage.html#cb216-1" aria-hidden="true" tabindex="-1"></a>.<span class="kw">tables</span></span>
<span id="cb216-2"><a href="data-collection-and-data-storage.html#cb216-2" aria-hidden="true" tabindex="-1"></a>.<span class="kw">schema</span> flights</span></code></pre></div>
<p>In <code>flights</code>, each row describes a flight (the day it took place, its origin, its destination etc.). It contains a covariate <code>carrier</code> containing the unique ID of the respective airline/carrier carrying out the flight as well as the covariates <code>origin</code> and <code>dest</code>. The latter two variables contain the unique IATA-codes of the airports from which the flights departed and where they arrived, respectively. In <code>flights</code> we thus have observations at the level of individual flights.</p>
<p>Now we extend our database in a meaningful way, following the relational data model idea. First we download two additional csv files containing data that relate to the flights table:</p>
<ul>
<li><a href="http://stat-computing.org/dataexpo/2009/airports.csv"><code>airports.csv</code></a>: Describes the locations of US Airports (relates to <code>origin</code> and <code>dest</code>).</li>
<li><a href="http://stat-computing.org/dataexpo/2009/carriers.csv"><code>carriers.csv</code></a>: A listing of carrier codes with full names (relates to the <code>carrier</code>-column in <code>flights</code>.</li>
</ul>
<p>In this code example, the two csvs have already been downloaded to the <code>materials/data</code>-folder.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb217-1"><a href="data-collection-and-data-storage.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- import airport data</span></span>
<span id="cb217-2"><a href="data-collection-and-data-storage.html#cb217-2" aria-hidden="true" tabindex="-1"></a>.<span class="kw">mode</span> csv</span>
<span id="cb217-3"><a href="data-collection-and-data-storage.html#cb217-3" aria-hidden="true" tabindex="-1"></a>.import airports.csv airports</span>
<span id="cb217-4"><a href="data-collection-and-data-storage.html#cb217-4" aria-hidden="true" tabindex="-1"></a>.import carriers.csv carriers</span>
<span id="cb217-5"><a href="data-collection-and-data-storage.html#cb217-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb217-6"><a href="data-collection-and-data-storage.html#cb217-6" aria-hidden="true" tabindex="-1"></a><span class="co">-- inspect the result</span></span>
<span id="cb217-7"><a href="data-collection-and-data-storage.html#cb217-7" aria-hidden="true" tabindex="-1"></a>.<span class="kw">tables</span></span>
<span id="cb217-8"><a href="data-collection-and-data-storage.html#cb217-8" aria-hidden="true" tabindex="-1"></a>.<span class="kw">schema</span> airports</span>
<span id="cb217-9"><a href="data-collection-and-data-storage.html#cb217-9" aria-hidden="true" tabindex="-1"></a>.<span class="kw">schema</span> carriers</span></code></pre></div>
<p>Now we can run our first query involving the relation between tables. The aim of the exercise is to query flights data (information on departure delays per flight number and date; from the <code>flights</code>-table) for all <code>United Air Lines Inc.</code>-flights (information from the <code>carriers</code> table ) departing from <code>Newark Intl</code> airport (information from the <code>airports</code>-table). In addition, we want the resulting table ordered by flight number. For the sake of the exercise, we only show the first 10 results of this query (<code>LIMIT 10</code>).</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb218-1"><a href="data-collection-and-data-storage.html#cb218-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> </span>
<span id="cb218-2"><a href="data-collection-and-data-storage.html#cb218-2" aria-hidden="true" tabindex="-1"></a><span class="dt">year</span>,</span>
<span id="cb218-3"><a href="data-collection-and-data-storage.html#cb218-3" aria-hidden="true" tabindex="-1"></a><span class="dt">month</span>, </span>
<span id="cb218-4"><a href="data-collection-and-data-storage.html#cb218-4" aria-hidden="true" tabindex="-1"></a><span class="dt">day</span>,</span>
<span id="cb218-5"><a href="data-collection-and-data-storage.html#cb218-5" aria-hidden="true" tabindex="-1"></a>dep_delay,</span>
<span id="cb218-6"><a href="data-collection-and-data-storage.html#cb218-6" aria-hidden="true" tabindex="-1"></a>flight</span>
<span id="cb218-7"><a href="data-collection-and-data-storage.html#cb218-7" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> (flights <span class="kw">INNER</span> <span class="kw">JOIN</span> airports <span class="kw">ON</span> flights.origin<span class="op">=</span>airports.iata) </span>
<span id="cb218-8"><a href="data-collection-and-data-storage.html#cb218-8" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> carriers <span class="kw">ON</span> flights.carrier <span class="op">=</span> carriers.Code</span>
<span id="cb218-9"><a href="data-collection-and-data-storage.html#cb218-9" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> carriers.Description <span class="op">=</span> <span class="st">&#39;United Air Lines Inc.&#39;</span></span>
<span id="cb218-10"><a href="data-collection-and-data-storage.html#cb218-10" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> airports.airport <span class="op">=</span> <span class="st">&#39;Newark Intl&#39;</span></span>
<span id="cb218-11"><a href="data-collection-and-data-storage.html#cb218-11" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> flight</span>
<span id="cb218-12"><a href="data-collection-and-data-storage.html#cb218-12" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code></pre></div>
<div class="knitsql-table">
<table>
<caption><span id="tab:unnamed-chunk-125">Table 10.1: </span>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">month</th>
<th align="right">day</th>
<th align="right">dep_delay</th>
<th align="right">flight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">-2</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">13</td>
<td align="right">-2</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">16</td>
<td align="right">-9</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">20</td>
<td align="right">3</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">23</td>
<td align="right">-5</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">26</td>
<td align="right">24</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">27</td>
<td align="right">10</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">10</td>
</tr>
</tbody>
</table>
</div>
<p>Note that this query has been executed without indexing any of the tables first. Thus SQLite could not take any ‘shortcuts’ when matching the ID columns in order to join the tables for the query output. That is, SQLite had to scan the entire columns to find the matches. Now we index the respective id columns and re-run the query.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb219-1"><a href="data-collection-and-data-storage.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">INDEX</span> iata_airports <span class="kw">ON</span> airports (iata);</span>
<span id="cb219-2"><a href="data-collection-and-data-storage.html#cb219-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">INDEX</span> origin_flights <span class="kw">ON</span> flights (origin);</span>
<span id="cb219-3"><a href="data-collection-and-data-storage.html#cb219-3" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">INDEX</span> carrier_flights <span class="kw">ON</span> flights (carrier);</span>
<span id="cb219-4"><a href="data-collection-and-data-storage.html#cb219-4" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">INDEX</span> code_carriers <span class="kw">ON</span> carriers (code);</span></code></pre></div>
<p>Note that SQLite optimizes the efficiency of the query without our explicit instructions. If there are indices it can use to speed up the query, it will do so.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb220-1"><a href="data-collection-and-data-storage.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> </span>
<span id="cb220-2"><a href="data-collection-and-data-storage.html#cb220-2" aria-hidden="true" tabindex="-1"></a><span class="dt">year</span>,</span>
<span id="cb220-3"><a href="data-collection-and-data-storage.html#cb220-3" aria-hidden="true" tabindex="-1"></a><span class="dt">month</span>, </span>
<span id="cb220-4"><a href="data-collection-and-data-storage.html#cb220-4" aria-hidden="true" tabindex="-1"></a><span class="dt">day</span>,</span>
<span id="cb220-5"><a href="data-collection-and-data-storage.html#cb220-5" aria-hidden="true" tabindex="-1"></a>dep_delay,</span>
<span id="cb220-6"><a href="data-collection-and-data-storage.html#cb220-6" aria-hidden="true" tabindex="-1"></a>flight</span>
<span id="cb220-7"><a href="data-collection-and-data-storage.html#cb220-7" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> (flights <span class="kw">INNER</span> <span class="kw">JOIN</span> airports <span class="kw">ON</span> flights.origin<span class="op">=</span>airports.iata) </span>
<span id="cb220-8"><a href="data-collection-and-data-storage.html#cb220-8" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> carriers <span class="kw">ON</span> flights.carrier <span class="op">=</span> carriers.Code</span>
<span id="cb220-9"><a href="data-collection-and-data-storage.html#cb220-9" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> carriers.Description <span class="op">=</span> <span class="st">&#39;United Air Lines Inc.&#39;</span></span>
<span id="cb220-10"><a href="data-collection-and-data-storage.html#cb220-10" aria-hidden="true" tabindex="-1"></a><span class="kw">AND</span> airports.airport <span class="op">=</span> <span class="st">&#39;Newark Intl&#39;</span></span>
<span id="cb220-11"><a href="data-collection-and-data-storage.html#cb220-11" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> flight</span>
<span id="cb220-12"><a href="data-collection-and-data-storage.html#cb220-12" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code></pre></div>
<div class="knitsql-table">
<table>
<caption><span id="tab:unnamed-chunk-127">Table 10.2: </span>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">month</th>
<th align="right">day</th>
<th align="right">dep_delay</th>
<th align="right">flight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">-2</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">13</td>
<td align="right">-2</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">16</td>
<td align="right">-9</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">20</td>
<td align="right">3</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">23</td>
<td align="right">-5</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">26</td>
<td align="right">24</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2013</td>
<td align="right">2</td>
<td align="right">27</td>
<td align="right">10</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">2013</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">10</td>
</tr>
</tbody>
</table>
</div>
<p>You find the final <code>air.sqlite</code>, including all the indices and tables as <code>materials/data/air_final.sqlite</code> in the course’s code repository.</p>
</div>
</div>
<div id="connecting-r-to-rdbms" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Connecting R to RDBMS<a href="data-collection-and-data-storage.html#connecting-r-to-rdbms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The R-package <code>RSQLite</code> embeds SQLite in R. That is, it provides functions that allow us to use SQLite directly from within R. You will see that the combinaiton of SQLite with R is a simple but very practical approach to work with very efficiently (and locally) stored data sets. In the following example, we explore how <code>RSQLite</code> can be used to set up and query the <code>air.sqlite</code> shown in the example above.</p>
<div id="creating-a-new-database-with-rsqlite" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Creating a new database with <code>RSQLite</code><a href="data-collection-and-data-storage.html#creating-a-new-database-with-rsqlite" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similarly to the raw SQLite-syntax, connecting to a database that does not exist yet, actually creates this (empty database). Note that for all interactions with the database from within R, we need to refer to the connection (here: <code>con_air</code>).</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="data-collection-and-data-storage.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb221-2"><a href="data-collection-and-data-storage.html#cb221-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RSQLite)</span>
<span id="cb221-3"><a href="data-collection-and-data-storage.html#cb221-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb221-4"><a href="data-collection-and-data-storage.html#cb221-4" aria-hidden="true" tabindex="-1"></a><span class="co"># initiate the database</span></span>
<span id="cb221-5"><a href="data-collection-and-data-storage.html#cb221-5" aria-hidden="true" tabindex="-1"></a>con_air <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="fu">SQLite</span>(), <span class="st">&quot;data/air.sqlite&quot;</span>)</span></code></pre></div>
</div>
<div id="importing-data" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Importing data<a href="data-collection-and-data-storage.html#importing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>RSQLite</code> we can easily add <code>data.frame</code>s as SQLite tables to the database.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="data-collection-and-data-storage.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import data into current R sesssion</span></span>
<span id="cb222-2"><a href="data-collection-and-data-storage.html#cb222-2" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/flights.csv&quot;</span>)</span>
<span id="cb222-3"><a href="data-collection-and-data-storage.html#cb222-3" aria-hidden="true" tabindex="-1"></a>airports <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/airports.csv&quot;</span>)</span>
<span id="cb222-4"><a href="data-collection-and-data-storage.html#cb222-4" aria-hidden="true" tabindex="-1"></a>carriers <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/carriers.csv&quot;</span>)</span>
<span id="cb222-5"><a href="data-collection-and-data-storage.html#cb222-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-6"><a href="data-collection-and-data-storage.html#cb222-6" aria-hidden="true" tabindex="-1"></a><span class="co"># add tables to database</span></span>
<span id="cb222-7"><a href="data-collection-and-data-storage.html#cb222-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_air, <span class="st">&quot;flights&quot;</span>, flights)</span>
<span id="cb222-8"><a href="data-collection-and-data-storage.html#cb222-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_air, <span class="st">&quot;airports&quot;</span>, airports)</span>
<span id="cb222-9"><a href="data-collection-and-data-storage.html#cb222-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_air, <span class="st">&quot;carriers&quot;</span>, carriers)</span></code></pre></div>
</div>
<div id="issue-queries" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Issue queries<a href="data-collection-and-data-storage.html#issue-queries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we can query the database from within R. By default, <code>RSQLite</code> returns the query results as <code>data.frame</code>s. Queries are simply character strings written in SQLite.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="data-collection-and-data-storage.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define query</span></span>
<span id="cb223-2"><a href="data-collection-and-data-storage.html#cb223-2" aria-hidden="true" tabindex="-1"></a>delay_query <span class="ot">&lt;-</span></span>
<span id="cb223-3"><a href="data-collection-and-data-storage.html#cb223-3" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;SELECT </span></span>
<span id="cb223-4"><a href="data-collection-and-data-storage.html#cb223-4" aria-hidden="true" tabindex="-1"></a><span class="st">year,</span></span>
<span id="cb223-5"><a href="data-collection-and-data-storage.html#cb223-5" aria-hidden="true" tabindex="-1"></a><span class="st">month, </span></span>
<span id="cb223-6"><a href="data-collection-and-data-storage.html#cb223-6" aria-hidden="true" tabindex="-1"></a><span class="st">day,</span></span>
<span id="cb223-7"><a href="data-collection-and-data-storage.html#cb223-7" aria-hidden="true" tabindex="-1"></a><span class="st">dep_delay,</span></span>
<span id="cb223-8"><a href="data-collection-and-data-storage.html#cb223-8" aria-hidden="true" tabindex="-1"></a><span class="st">flight</span></span>
<span id="cb223-9"><a href="data-collection-and-data-storage.html#cb223-9" aria-hidden="true" tabindex="-1"></a><span class="st">FROM (flights INNER JOIN airports ON flights.origin=airports.iata) </span></span>
<span id="cb223-10"><a href="data-collection-and-data-storage.html#cb223-10" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN carriers ON flights.carrier = carriers.Code</span></span>
<span id="cb223-11"><a href="data-collection-and-data-storage.html#cb223-11" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE carriers.Description = &#39;United Air Lines Inc.&#39;</span></span>
<span id="cb223-12"><a href="data-collection-and-data-storage.html#cb223-12" aria-hidden="true" tabindex="-1"></a><span class="st">AND airports.airport = &#39;Newark Intl&#39;</span></span>
<span id="cb223-13"><a href="data-collection-and-data-storage.html#cb223-13" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY flight</span></span>
<span id="cb223-14"><a href="data-collection-and-data-storage.html#cb223-14" aria-hidden="true" tabindex="-1"></a><span class="st">LIMIT 10;</span></span>
<span id="cb223-15"><a href="data-collection-and-data-storage.html#cb223-15" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb223-16"><a href="data-collection-and-data-storage.html#cb223-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb223-17"><a href="data-collection-and-data-storage.html#cb223-17" aria-hidden="true" tabindex="-1"></a><span class="co"># issue query</span></span>
<span id="cb223-18"><a href="data-collection-and-data-storage.html#cb223-18" aria-hidden="true" tabindex="-1"></a>delays_df <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con_air, delay_query)</span>
<span id="cb223-19"><a href="data-collection-and-data-storage.html#cb223-19" aria-hidden="true" tabindex="-1"></a>delays_df</span></code></pre></div>
<p>When done working with the database, we close the connection to the database with <code>dbDisconnect(con)</code>.</p>
</div>
</div>
<div id="cloud-solutions-for-big-data-storage" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Cloud solutions for (big) data storage<a href="data-collection-and-data-storage.html#cloud-solutions-for-big-data-storage" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As outlined in the previous section, RDBMSs are a very practical tool to store the structured data of an analytics project locally in a database. A local SQLite database can easily be set up and accessed via R, allowing to write the whole data pipeline from data gathering to filtering, aggregating and finally analyzing in R. In contrast to directly working with CSV files, using SQLite has the advantage of organizing the data access much more efficiently in terms of RAM. Only the final result of a query is really loaded fully into R’s memory.</p>
<p>If mass storage space is too sparse or if RAM is nevertheless not sufficient, even when organizing data access via SQLite, several cloud solutions come to the rescue. Although you could also rent a traditional web server and host a SQL database there, this is usually not worth the while for a data analytics project. In the next section we thus look at three important cases of how to store data as part of an analytics project: <em>RDBMS in the cloud</em>, a serverless <em>data warehouse</em> solution for large datasets called <em>Google BigQuery</em>, and a simple storage service to use as a <em>data lake</em> called <em>AWS S3</em>. All of these solutions are discussed from a data analytics perspective, and for all of these solutions we will look at how to make use of them from within R.</p>
<div id="easy-to-use-rdbms-in-the-cloud-aws-rds" class="section level3 hasAnchor" number="10.5.1">
<h3><span class="header-section-number">10.5.1</span> Easy-to-use RDBMS in the cloud: AWS RDS<a href="data-collection-and-data-storage.html#easy-to-use-rdbms-in-the-cloud-aws-rds" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once we have set up RStudio Server on an EC2 instance, we can run the SQLite examples shown above on it. There are no additional steps needed to install SQLite. However, when using RDBMSs in the cloud, we typically have a more sophisticated implementation than SQLite in mind. Particularly, we want to set up an actual RDBMS-server running in the cloud to which several clients can connect (e.g., via RStudio Server).</p>
<p>AWS’ Relational Database Service (RDS) provides an easy way to set up and run a SQL database in the cloud. The great advantage for users new to RDBMS/SQL is that you do not have to manually set up a server (e.g. a EC2 instance) and install/configure the SQL server. Instead you can directly set up a fully functioning relational database in the cloud.</p>
<p>In a first step, open the AWS console and search for/select “RDS” in the search bar. Then, click on “Create database” in the lower part of the landing page.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rdscreate"></span>
<img src="img/aws_rds_create.png" alt="Create a managed relational database on AWS RDS." width="80%" />
<p class="caption">
Figure 10.1: Create a managed relational database on AWS RDS.
</p>
</div>

<p>On the next page, select “Easy create”, “MySQL”, and the “Free tier” DB instance size. Further down you will have to set the database instance identifier the user name and a password.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rdseasy"></span>
<img src="img/aws_rds_easycreate.png" alt="Easy creation of a RDS MySQL DB." width="80%" />
<p class="caption">
Figure 10.2: Easy creation of a RDS MySQL DB.
</p>
</div>

<p>Once the database instance is ready, you will see it in the databases overview. Click on the DB identifier (the name of your database shown in the list of databases) and click on modify (button in the upper-right corner). In the “Connectivity” panel under “Additional configuration”, select <em>Publicly accessible</em> (this is necessary to interact with the DB from your local machine), and save the settings. Back on the overview page of your database, under “Connectivity &amp; security”, click on the link under the VPC security groups, scroll down and select the “Inbound rules” tab. Edit the inbound rule to allow any IP4 inbound traffic.<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rdsinboundrules"></span>
<img src="img/rds_inboundrules.png" alt="Allow all IP4 inbound traffic (set Source to 0.0.0.0/0)." width="80%" />
<p class="caption">
Figure 10.3: Allow all IP4 inbound traffic (set Source to <code>0.0.0.0/0</code>).
</p>
</div>

<p>Now we can connect to the instance via the <code>RMySQL</code> package. Before loading data, we first have to initiate a new database (in contrast, this is done automatically when connecting to a SQLite database).</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="data-collection-and-data-storage.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb224-2"><a href="data-collection-and-data-storage.html#cb224-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RMySQL)</span>
<span id="cb224-3"><a href="data-collection-and-data-storage.html#cb224-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb224-4"><a href="data-collection-and-data-storage.html#cb224-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-5"><a href="data-collection-and-data-storage.html#cb224-5" aria-hidden="true" tabindex="-1"></a><span class="co"># fix vars</span></span>
<span id="cb224-6"><a href="data-collection-and-data-storage.html#cb224-6" aria-hidden="true" tabindex="-1"></a>RDS_ENDPOINT <span class="ot">&lt;-</span> <span class="st">&quot;MY-ENDPOINT&quot;</span> <span class="co"># replace this with the Endpoint shown in the AWS RDS console</span></span>
<span id="cb224-7"><a href="data-collection-and-data-storage.html#cb224-7" aria-hidden="true" tabindex="-1"></a>PW <span class="ot">&lt;-</span> <span class="st">&quot;MY-PW&quot;</span> <span class="co"># replace this with the password you have set when initiating the RDS DB on AWS</span></span>
<span id="cb224-8"><a href="data-collection-and-data-storage.html#cb224-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-9"><a href="data-collection-and-data-storage.html#cb224-9" aria-hidden="true" tabindex="-1"></a><span class="co"># connect to DB</span></span>
<span id="cb224-10"><a href="data-collection-and-data-storage.html#cb224-10" aria-hidden="true" tabindex="-1"></a>con_rds <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(),</span>
<span id="cb224-11"><a href="data-collection-and-data-storage.html#cb224-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">host=</span>RDS_ENDPOINT,</span>
<span id="cb224-12"><a href="data-collection-and-data-storage.html#cb224-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">port=</span><span class="dv">3306</span>,</span>
<span id="cb224-13"><a href="data-collection-and-data-storage.html#cb224-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">username=</span><span class="st">&quot;admin&quot;</span>,</span>
<span id="cb224-14"><a href="data-collection-and-data-storage.html#cb224-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">password=</span>PW)</span>
<span id="cb224-15"><a href="data-collection-and-data-storage.html#cb224-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-16"><a href="data-collection-and-data-storage.html#cb224-16" aria-hidden="true" tabindex="-1"></a><span class="co"># initiate a new database on the MySQL RDS instance</span></span>
<span id="cb224-17"><a href="data-collection-and-data-storage.html#cb224-17" aria-hidden="true" tabindex="-1"></a><span class="fu">dbSendQuery</span>(con_rds, <span class="st">&quot;CREATE DATABASE air&quot;</span>)</span>
<span id="cb224-18"><a href="data-collection-and-data-storage.html#cb224-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-19"><a href="data-collection-and-data-storage.html#cb224-19" aria-hidden="true" tabindex="-1"></a><span class="co"># disconnect and re-connect directly to the new DB</span></span>
<span id="cb224-20"><a href="data-collection-and-data-storage.html#cb224-20" aria-hidden="true" tabindex="-1"></a><span class="fu">dbDisconnect</span>(con_rds)</span>
<span id="cb224-21"><a href="data-collection-and-data-storage.html#cb224-21" aria-hidden="true" tabindex="-1"></a>con_rds <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(),</span>
<span id="cb224-22"><a href="data-collection-and-data-storage.html#cb224-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">host=</span>RDS_ENDPOINT,</span>
<span id="cb224-23"><a href="data-collection-and-data-storage.html#cb224-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">port=</span><span class="dv">3306</span>,</span>
<span id="cb224-24"><a href="data-collection-and-data-storage.html#cb224-24" aria-hidden="true" tabindex="-1"></a>                 <span class="at">username=</span><span class="st">&quot;admin&quot;</span>,</span>
<span id="cb224-25"><a href="data-collection-and-data-storage.html#cb224-25" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dbname=</span><span class="st">&quot;air&quot;</span>,</span>
<span id="cb224-26"><a href="data-collection-and-data-storage.html#cb224-26" aria-hidden="true" tabindex="-1"></a>                 <span class="at">password=</span>PW)</span></code></pre></div>
<p><code>RMySQL</code> and <code>RSQLite</code> are both building on the <code>DBI</code> package, which generalizes how we can interact with SQL-type databases via R. This makes it straightforward to apply what we have learned so far by interacting with our local SQLite database to interactions with other databases. As soon as the connection to the new database is established, we can essentially use the same R functions as above to create new tables and import data.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="data-collection-and-data-storage.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import data into current R sesssion</span></span>
<span id="cb225-2"><a href="data-collection-and-data-storage.html#cb225-2" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/flights.csv&quot;</span>)</span>
<span id="cb225-3"><a href="data-collection-and-data-storage.html#cb225-3" aria-hidden="true" tabindex="-1"></a>airports <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/airports.csv&quot;</span>)</span>
<span id="cb225-4"><a href="data-collection-and-data-storage.html#cb225-4" aria-hidden="true" tabindex="-1"></a>carriers <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/carriers.csv&quot;</span>)</span>
<span id="cb225-5"><a href="data-collection-and-data-storage.html#cb225-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb225-6"><a href="data-collection-and-data-storage.html#cb225-6" aria-hidden="true" tabindex="-1"></a><span class="co"># add tables to database</span></span>
<span id="cb225-7"><a href="data-collection-and-data-storage.html#cb225-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_rds, <span class="st">&quot;flights&quot;</span>, flights)</span>
<span id="cb225-8"><a href="data-collection-and-data-storage.html#cb225-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_rds, <span class="st">&quot;airports&quot;</span>, airports)</span>
<span id="cb225-9"><a href="data-collection-and-data-storage.html#cb225-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dbWriteTable</span>(con_rds, <span class="st">&quot;carriers&quot;</span>, carriers)</span></code></pre></div>
<p>Finally, we can query our RDS MySQL database on AWS.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="data-collection-and-data-storage.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define query</span></span>
<span id="cb226-2"><a href="data-collection-and-data-storage.html#cb226-2" aria-hidden="true" tabindex="-1"></a>delay_query <span class="ot">&lt;-</span></span>
<span id="cb226-3"><a href="data-collection-and-data-storage.html#cb226-3" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;SELECT </span></span>
<span id="cb226-4"><a href="data-collection-and-data-storage.html#cb226-4" aria-hidden="true" tabindex="-1"></a><span class="st">year,</span></span>
<span id="cb226-5"><a href="data-collection-and-data-storage.html#cb226-5" aria-hidden="true" tabindex="-1"></a><span class="st">month, </span></span>
<span id="cb226-6"><a href="data-collection-and-data-storage.html#cb226-6" aria-hidden="true" tabindex="-1"></a><span class="st">day,</span></span>
<span id="cb226-7"><a href="data-collection-and-data-storage.html#cb226-7" aria-hidden="true" tabindex="-1"></a><span class="st">dep_delay,</span></span>
<span id="cb226-8"><a href="data-collection-and-data-storage.html#cb226-8" aria-hidden="true" tabindex="-1"></a><span class="st">flight</span></span>
<span id="cb226-9"><a href="data-collection-and-data-storage.html#cb226-9" aria-hidden="true" tabindex="-1"></a><span class="st">FROM (flights INNER JOIN airports ON flights.origin=airports.iata) </span></span>
<span id="cb226-10"><a href="data-collection-and-data-storage.html#cb226-10" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN carriers ON flights.carrier = carriers.Code</span></span>
<span id="cb226-11"><a href="data-collection-and-data-storage.html#cb226-11" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE carriers.Description = &#39;United Air Lines Inc.&#39;</span></span>
<span id="cb226-12"><a href="data-collection-and-data-storage.html#cb226-12" aria-hidden="true" tabindex="-1"></a><span class="st">AND airports.airport = &#39;Newark Intl&#39;</span></span>
<span id="cb226-13"><a href="data-collection-and-data-storage.html#cb226-13" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY flight</span></span>
<span id="cb226-14"><a href="data-collection-and-data-storage.html#cb226-14" aria-hidden="true" tabindex="-1"></a><span class="st">LIMIT 10;</span></span>
<span id="cb226-15"><a href="data-collection-and-data-storage.html#cb226-15" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb226-16"><a href="data-collection-and-data-storage.html#cb226-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb226-17"><a href="data-collection-and-data-storage.html#cb226-17" aria-hidden="true" tabindex="-1"></a><span class="co"># issue query</span></span>
<span id="cb226-18"><a href="data-collection-and-data-storage.html#cb226-18" aria-hidden="true" tabindex="-1"></a>delays_df <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con_rds, delay_query)</span>
<span id="cb226-19"><a href="data-collection-and-data-storage.html#cb226-19" aria-hidden="true" tabindex="-1"></a>delays_df</span></code></pre></div>
</div>
<div id="database-server-in-the-cloud-mariadb-on-an-ec2-instance" class="section level3 hasAnchor" number="10.5.2">
<h3><span class="header-section-number">10.5.2</span> Database server in the cloud: MariaDB on an EC2 instance<a href="data-collection-and-data-storage.html#database-server-in-the-cloud-mariadb-on-an-ec2-instance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Working with an SQL database in the cloud via AWS RDS is probably sufficient for most simple use cases. However, for some projects you might want to have more flexibility regarding settings and configurations. A practical solution to this is to set up “manually” a SQL-server on an EC2 instance (and then work with it via RStudio-Server). The following example, based on <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>, guides you through the first step to set up such a database in the cloud. For most of the installation steps you are referred to the respective pages in <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span> (Chapter 5: ’MariaDB with R on a Amazon EC2 instance, pages 255ff). However, since some of the steps shown in the book are outdated, the example below hints to some alternative/additional steps needed to make the database run on an Ubuntu 18.04 machine.</p>
<p>After launching the EC2 instance on AWS, use the following terminal commands to install R:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb227-1"><a href="data-collection-and-data-storage.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="co"># update ubuntu packages</span></span>
<span id="cb227-2"><a href="data-collection-and-data-storage.html#cb227-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">sudo</span> apt-get update</span>
<span id="cb227-3"><a href="data-collection-and-data-storage.html#cb227-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">sudo</span> apt-get upgrade</span></code></pre></div>
<div class="sourceCode" id="cb228"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb228-1"><a href="data-collection-and-data-storage.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt-get install r-base</span></code></pre></div>
<p>and to install RStudio Server (on Ubuntu 18.04, as of April 2020):</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb229-1"><a href="data-collection-and-data-storage.html#cb229-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt-get install gdebi-core</span>
<span id="cb229-2"><a href="data-collection-and-data-storage.html#cb229-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.5033-amd64.deb</span>
<span id="cb229-3"><a href="data-collection-and-data-storage.html#cb229-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> gdebi rstudio-server-1.2.5033-amd64.deb</span></code></pre></div>
<p>Following <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span> (pages 257f), we first set up a new user and give it permissions to <code>ssh</code> directly to the EC2 instance (this way we can then more easily upload data ‘for this user’).</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb230-1"><a href="data-collection-and-data-storage.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create user</span></span>
<span id="cb230-2"><a href="data-collection-and-data-storage.html#cb230-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> adduser umatter </span></code></pre></div>
<p>When prompted for additional information just hit enter (for default). Now we can grant the user the permissions</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb231-1"><a href="data-collection-and-data-storage.html#cb231-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> cp <span class="at">-r</span> /home/ubuntu/.ssh /home/umatter/</span>
<span id="cb231-2"><a href="data-collection-and-data-storage.html#cb231-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> /home/umatter/</span>
<span id="cb231-3"><a href="data-collection-and-data-storage.html#cb231-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> chown <span class="at">-R</span> umatter:umatter .ssh</span></code></pre></div>
<p>Then install MariaDB as follows.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb232-1"><a href="data-collection-and-data-storage.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt update</span>
<span id="cb232-2"><a href="data-collection-and-data-storage.html#cb232-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt install mariadb-server</span>
<span id="cb232-3"><a href="data-collection-and-data-storage.html#cb232-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt install libmariadbclient-dev</span>
<span id="cb232-4"><a href="data-collection-and-data-storage.html#cb232-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> apt install libxml2-dev <span class="co"># needed later (dependency for some R packages)</span></span></code></pre></div>
<p>If prompted to set a password for the root database user (user with all database priviledges), type in and confirm the chosen password.<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a></p>
<div id="data-import" class="section level4 hasAnchor" number="10.5.2.1">
<h4><span class="header-section-number">10.5.2.1</span> Data import<a href="data-collection-and-data-storage.html#data-import" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With the permissions set above, we can send data from the local machine directly to the instance via <code>ssh</code>. We use this to first transfer the raw data to the instance and then import it to the database.</p>
<p>The aim is to import the same simple data set <code>economics.csv</code> used in the local SQLite examples of Lecture 7. Following the instructions of <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>, pages 252 to 254, we upload the <code>economics.csv</code> file (instead of the example data used in <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>). Note that in all the code examples below, the username is <code>umatter</code>, and the IP-address will have to be replaced with the public IP-address of your EC2 instance.</p>
<p>Open a new terminal window and send the <code>economics.csv</code> data as follows to the instance.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb233-1"><a href="data-collection-and-data-storage.html#cb233-1" aria-hidden="true" tabindex="-1"></a><span class="co"># from the directory where the key-file is stored...</span></span>
<span id="cb233-2"><a href="data-collection-and-data-storage.html#cb233-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scp</span> <span class="at">-r</span> <span class="at">-i</span> <span class="st">&quot;mariadb_ec2.pem&quot;</span> ~/Desktop/economics.csv umatter@ec2-184-72-202-166.compute-1.amazonaws.com:~/</span></code></pre></div>
<p>Then switch back to the terminal connected to the instance and start the MariaDB server.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb234-1"><a href="data-collection-and-data-storage.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="co"># start the MariaDB server</span></span>
<span id="cb234-2"><a href="data-collection-and-data-storage.html#cb234-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> service mysql start</span>
<span id="cb234-3"><a href="data-collection-and-data-storage.html#cb234-3" aria-hidden="true" tabindex="-1"></a><span class="co"># log into the MariaDB client as root </span></span>
<span id="cb234-4"><a href="data-collection-and-data-storage.html#cb234-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> mysql <span class="at">-uroot</span> </span></code></pre></div>
<p>If not prompted to do so when installing MariaDB (see above), add a new root user in order to login to MariaDB without the <code>sudo</code> (here we simply set the password to ‘Password1’).</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb235-1"><a href="data-collection-and-data-storage.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="kw">GRANT</span> <span class="kw">ALL</span> <span class="kw">PRIVILEGES</span> <span class="kw">on</span> <span class="op">*</span>.<span class="op">*</span> <span class="kw">to</span> <span class="st">&#39;root&#39;</span>@<span class="st">&#39;localhost&#39;</span> <span class="kw">IDENTIFIED</span> <span class="kw">BY</span> <span class="st">&#39;Password1&#39;</span>;</span>
<span id="cb235-2"><a href="data-collection-and-data-storage.html#cb235-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FLUSH</span> <span class="kw">PRIVILEGES</span>;</span></code></pre></div>
<p>Restart the mysql server and log in with the database root user.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb236-1"><a href="data-collection-and-data-storage.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="co"># start the MariaDB server</span></span>
<span id="cb236-2"><a href="data-collection-and-data-storage.html#cb236-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> service mysql restart</span>
<span id="cb236-3"><a href="data-collection-and-data-storage.html#cb236-3" aria-hidden="true" tabindex="-1"></a><span class="co"># log into the MariaDB client as root </span></span>
<span id="cb236-4"><a href="data-collection-and-data-storage.html#cb236-4" aria-hidden="true" tabindex="-1"></a><span class="ex">mysql</span> <span class="at">-uroot</span> <span class="at">-p</span></span></code></pre></div>
<p>Now we can initiate a new database called <code>data1</code>.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb237-1"><a href="data-collection-and-data-storage.html#cb237-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">database</span> data1;</span></code></pre></div>
<p>To work with the newly created database, we have to ‘select’ it.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb238-1"><a href="data-collection-and-data-storage.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="kw">USE</span> data1;</span></code></pre></div>
<p>Then, we create the first table of our database and import data into it. Note that we only have to slightly adjust the former SQLite syntax to make this work (remove double quotes for field names). In addition, note that we can use the same field types as in the SQLite DB.<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a></p>
<div class="sourceCode" id="cb239"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb239-1"><a href="data-collection-and-data-storage.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Create the new table</span></span>
<span id="cb239-2"><a href="data-collection-and-data-storage.html#cb239-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> econ(</span>
<span id="cb239-3"><a href="data-collection-and-data-storage.html#cb239-3" aria-hidden="true" tabindex="-1"></a><span class="dt">date</span> <span class="dt">DATE</span>,</span>
<span id="cb239-4"><a href="data-collection-and-data-storage.html#cb239-4" aria-hidden="true" tabindex="-1"></a>pce <span class="dt">REAL</span>,</span>
<span id="cb239-5"><a href="data-collection-and-data-storage.html#cb239-5" aria-hidden="true" tabindex="-1"></a>pop <span class="dt">INTEGER</span>,</span>
<span id="cb239-6"><a href="data-collection-and-data-storage.html#cb239-6" aria-hidden="true" tabindex="-1"></a>psavert <span class="dt">REAL</span>,</span>
<span id="cb239-7"><a href="data-collection-and-data-storage.html#cb239-7" aria-hidden="true" tabindex="-1"></a>uempmed <span class="dt">REAL</span>,</span>
<span id="cb239-8"><a href="data-collection-and-data-storage.html#cb239-8" aria-hidden="true" tabindex="-1"></a>unemploy <span class="dt">INTEGER</span></span>
<span id="cb239-9"><a href="data-collection-and-data-storage.html#cb239-9" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div>
<p>After following the steps in <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>, pages 259-262, we can import the <code>economics.csv</code>-file to the <code>econ</code> table in MariaDB (again, assuming the username is <code>umatter</code>). Note that the syntax to import data to a table is quite different from the SQLite example in Lecture 7.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode sql"><code class="sourceCode sql"><span id="cb240-1"><a href="data-collection-and-data-storage.html#cb240-1" aria-hidden="true" tabindex="-1"></a>LOAD <span class="kw">DATA</span> <span class="kw">LOCAL</span> INFILE</span>
<span id="cb240-2"><a href="data-collection-and-data-storage.html#cb240-2" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;/home/umatter/economics.csv&#39;</span> </span>
<span id="cb240-3"><a href="data-collection-and-data-storage.html#cb240-3" aria-hidden="true" tabindex="-1"></a><span class="kw">INTO</span> <span class="kw">TABLE</span> econ</span>
<span id="cb240-4"><a href="data-collection-and-data-storage.html#cb240-4" aria-hidden="true" tabindex="-1"></a>FIELDS TERMINATED <span class="kw">BY</span> <span class="st">&#39;,&#39;</span></span>
<span id="cb240-5"><a href="data-collection-and-data-storage.html#cb240-5" aria-hidden="true" tabindex="-1"></a>LINES TERMINATED <span class="kw">BY</span> <span class="st">&#39;</span><span class="ch">\n</span><span class="st">&#39;</span></span>
<span id="cb240-6"><a href="data-collection-and-data-storage.html#cb240-6" aria-hidden="true" tabindex="-1"></a>IGNORE <span class="dv">1</span> <span class="kw">ROWS</span>;</span></code></pre></div>
<p>Now we can start using the newly created database from within RStudio Server running on our EC2 instance (following <span class="citation">Walkowiak (<a href="#ref-walkowiak_2016" role="doc-biblioref">2016</a>)</span>, pages 263ff).</p>
<p>As in the SQLite examples in Lecture 7, we can now query the database from within the R console (this time using <code>RMySQL</code> instead of <code>RSQLite</code>, and using R from within RStudio Server in the cloud!).</p>
<p>First, we need to connect to the newly created MariaDB database.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="data-collection-and-data-storage.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install package</span></span>
<span id="cb241-2"><a href="data-collection-and-data-storage.html#cb241-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;RMySQL&quot;)</span></span>
<span id="cb241-3"><a href="data-collection-and-data-storage.html#cb241-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb241-4"><a href="data-collection-and-data-storage.html#cb241-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RMySQL)</span>
<span id="cb241-5"><a href="data-collection-and-data-storage.html#cb241-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb241-6"><a href="data-collection-and-data-storage.html#cb241-6" aria-hidden="true" tabindex="-1"></a><span class="co"># connect to the db</span></span>
<span id="cb241-7"><a href="data-collection-and-data-storage.html#cb241-7" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(), </span>
<span id="cb241-8"><a href="data-collection-and-data-storage.html#cb241-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">user =</span> <span class="st">&quot;root&quot;</span>,</span>
<span id="cb241-9"><a href="data-collection-and-data-storage.html#cb241-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">password =</span> <span class="st">&quot;Password1&quot;</span>,</span>
<span id="cb241-10"><a href="data-collection-and-data-storage.html#cb241-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">host =</span> <span class="st">&quot;localhost&quot;</span>,</span>
<span id="cb241-11"><a href="data-collection-and-data-storage.html#cb241-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dbname =</span> <span class="st">&quot;data1&quot;</span>)</span></code></pre></div>
<p>In our first query, we select all (<code>*</code>) variable values of the observation of January 1968.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="data-collection-and-data-storage.html#cb242-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define the query</span></span>
<span id="cb242-2"><a href="data-collection-and-data-storage.html#cb242-2" aria-hidden="true" tabindex="-1"></a>query1 <span class="ot">&lt;-</span> </span>
<span id="cb242-3"><a href="data-collection-and-data-storage.html#cb242-3" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb242-4"><a href="data-collection-and-data-storage.html#cb242-4" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT * FROM econ</span></span>
<span id="cb242-5"><a href="data-collection-and-data-storage.html#cb242-5" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE date = &#39;1968-01-01&#39;;</span></span>
<span id="cb242-6"><a href="data-collection-and-data-storage.html#cb242-6" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb242-7"><a href="data-collection-and-data-storage.html#cb242-7" aria-hidden="true" tabindex="-1"></a><span class="co"># send the query to the db and get the result</span></span>
<span id="cb242-8"><a href="data-collection-and-data-storage.html#cb242-8" aria-hidden="true" tabindex="-1"></a>jan <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, query1)</span>
<span id="cb242-9"><a href="data-collection-and-data-storage.html#cb242-9" aria-hidden="true" tabindex="-1"></a>jan</span></code></pre></div>
<pre><code>#        date   pce    pop psavert uempmed unemploy
# 1 1968-01-01 531.5 199808    11.7     5.1     2878</code></pre>
<p>Now let’s select all year/months in which there were more than 15 million unemployed, ordered by date.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="data-collection-and-data-storage.html#cb244-1" aria-hidden="true" tabindex="-1"></a>query2 <span class="ot">&lt;-</span></span>
<span id="cb244-2"><a href="data-collection-and-data-storage.html#cb244-2" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb244-3"><a href="data-collection-and-data-storage.html#cb244-3" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT date FROM econ </span></span>
<span id="cb244-4"><a href="data-collection-and-data-storage.html#cb244-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE unemploy &gt; 15000</span></span>
<span id="cb244-5"><a href="data-collection-and-data-storage.html#cb244-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY date;</span></span>
<span id="cb244-6"><a href="data-collection-and-data-storage.html#cb244-6" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;</span></span>
<span id="cb244-7"><a href="data-collection-and-data-storage.html#cb244-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb244-8"><a href="data-collection-and-data-storage.html#cb244-8" aria-hidden="true" tabindex="-1"></a><span class="co"># send the query to the db and get the result</span></span>
<span id="cb244-9"><a href="data-collection-and-data-storage.html#cb244-9" aria-hidden="true" tabindex="-1"></a>unemp <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, query2)</span>
<span id="cb244-10"><a href="data-collection-and-data-storage.html#cb244-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(unemp)</span></code></pre></div>
<pre><code>#         date
# 1 2009-09-01
# 2 2009-10-01
# 3 2009-11-01
# 4 2009-12-01
# 5 2010-01-01
# 6 2010-02-01
</code></pre>
<p>When done working with the database, we close the connection to the MariaDB database with <code>dbDisconnect(con)</code>.</p>

</div>
</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-walkowiak_2016" class="csl-entry">
Walkowiak, Simkon. 2016. <em>Big Data Analytics with r</em>. Birmingham, UK: PACKT Publishing.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="36">
<li id="fn36"><p>Note that this is not generally recommendable. Only do this to get familiar with the service and to test some code.<a href="data-collection-and-data-storage.html#fnref36" class="footnote-back">↩︎</a></p></li>
<li id="fn37"><p>Below it is shown how to do this ‘manually’, if not promted at this step.<a href="data-collection-and-data-storage.html#fnref37" class="footnote-back">↩︎</a></p></li>
<li id="fn38"><p>However, MariaDB is a much more sophisticated RDBMS than SQLite and comes with many more field types, see the official <a href="https://mariadb.com/kb/en/library/data-types/">list of supported data types</a>.<a href="data-collection-and-data-storage.html#fnref38" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="forms-of-big-data-and-the-data-pipeline.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="big-data-cleaning-and-transformation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 1
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
